// The TBC raid encounters as Warcraft Logs numbers them, with their icons.
//
// `bossIcons.json` is generated by `node scripts/fetch-boss-icons.js`, which
// also drops the icon files into src/web-client/public/bosses/ (served at
// /bosses/<encounterId>.jpg by the built client). Don't hand-edit either.
const data = require("./bossIcons.json");

const BY_ID = new Map();
for (const zone of data.zones || []) {
    for (const enc of zone.encounters || []) BY_ID.set(Number(enc.id), { ...enc, zone: zone.name, zoneId: zone.id });
}

/** The site-relative icon url for an encounter id, or "" when it is not a known TBC boss. */
function bossIconUrl(encounterId) {
    const id = Number(encounterId);
    return BY_ID.has(id) ? `/bosses/${id}.jpg` : "";
}

/** WCL's English encounter name for an id, or "". */
function bossName(encounterId) {
    const enc = BY_ID.get(Number(encounterId));
    return enc ? enc.name : "";
}

module.exports = { bossIconUrl, bossName, ZONES: data.zones || [] };
