// Reference data for the WoW TBC log audit ("CLA" by Lars Maag / shariva).
//
// The data is generated by scripts/build-cla-data.js from the CLA Apps Script
// source and scripts/data-sources/cla/*.csv into config/generated/claData.json. Do not edit
// the JSON by hand; re-run the generator instead. The keys:
//
//   ENCHANTABLE_SLOTS       WCL/WoW equip slot indices that can carry a permanent enchant
//   GEM_QUALITY             gem quality name -> level ("minimum gem quality" setting, default rare)
//   META/YELLOW/RED/BLUE/UNCUT_GEM_IDS  gem item ids by colour
//   ACCEPTABLE_UNCOMMON/RARE_GEM_IDS    gems accepted despite hitting a quality threshold
//   ITEMS_WITHOUT_ENCHANT   items that take no (relevant) enchant, skipped by the no-enchant check
//   ENCHANT_BLACKLIST       suboptimal/cheap enchants: { id, slot|null, name }
//   EXCLUDED_GEAR           off-spec / joke gear excluded from the no-enchant check: { id, name }
//   SOCKETS                 itemId -> number of gem sockets
//   SHADOW_RESISTANCE       itemId -> shadow resistance (the Mother Shahraz check)
//   CONSUMABLES             consumable buff spell GUIDs per category (master config sheet)

module.exports = require("./generated/claData.json");
