// Reference data for the WoW TBC "Role Performance Breakdown" (RPB) by Lars Maag / shariva.
//
// The data is generated by scripts/build-rpb-data.js from scripts/data-sources/rpb/*.csv
// into config/generated/rpbData.json. Do not edit the JSON by hand; re-run the
// generator instead. The keys:
//
//   EXCLUDED_ENCOUNTER_ID     Kalecgos, excluded from every RPB number (two-realm fight breaks the maths)
//   HASTE_RATING_PER_PERCENT  TBC: 15.77 haste rating = 1% spell haste
//   HASTE_BUFFS               haste effects whose uses inflate the raw cast count; each use saves
//                             roughly `seconds` of cast time, subtracted before computing activity
//   HEADINGS                  German section headings taken from the config sheet
//   SPELL_HASTE_ITEMS         itemId -> spell haste rating (activity correction)
//   TRASH_REQUIREMENTS        zone tag -> trash that must be killed for a full clear
//   SINGLE_TARGET_CASTS, AOE_CASTS, CLASS_COOLDOWNS   per-class tracked casts
//   DAMAGE_TAKEN, DEBUFFS, STATS_AND_MISC, TRINKETS_AND_RACIALS, ENGINEERING,
//   OTHER_CASTS, ABSORBS      global tracked sections
//
// Entry shape: { name, label (German), ids: [spellId], icon?, lowerRankIds?, castTime?,
//                cooldown?, uptimeSeconds?, isUptime?, isOverheal? }

module.exports = require("./generated/rpbData.json");
