// Which TBC raid a looted item came from.
//
// The loot exports are unequal: RCLootcouncil names the instance and the boss,
// Gargul carries nothing but the item id. So the item id has to be the primary
// key — the RAID_LOOT table below maps every raid drop of the expansion to its
// content (and boss, where Wowhead attributes one). It is generated from the
// Wowhead zone drop tables by `node scripts/fetch-tbc-loot.js`; regenerate it
// instead of hand-editing the block.
//
// The export's own instance/boss strings are only the fallback for ids the
// table doesn't know (a world drop, a badge item, a future patch) — see
// contentForLoot().

// A raid tier groups the contents released together: the Tier-4/5/6 filter on
// the item list is exactly "everything from these raids". Zul'Aman shipped
// between T5 and T6 and drops no tier token of its own; it is filed under t5,
// where its item level and its raid week put it.
const TIERS = [
    { id: "t4", label: "Tier 4" },
    { id: "t5", label: "Tier 5" },
    { id: "t6", label: "Tier 6" },
    { id: "t65", label: "Sunwell" },
];

// `short` is what fits in a table badge, `label` what a filter dropdown shows.
// `zoneId` is the Wowhead zone the loot table was generated from.
const CONTENTS = [
    { id: "kara", label: "Karazhan", short: "Kara", tier: "t4", zoneId: 3457 },
    { id: "gruul", label: "Gruuls Unterschlupf", short: "Gruul", tier: "t4", zoneId: 3923 },
    { id: "mag", label: "Magtheridons Kammer", short: "Magtheridon", tier: "t4", zoneId: 3836 },
    { id: "ssc", label: "Höhle des Schlangenschreins", short: "SSC", tier: "t5", zoneId: 3607 },
    { id: "tk", label: "Festung der Stürme — Das Auge", short: "TK", tier: "t5", zoneId: 3845 },
    { id: "za", label: "Zul'Aman", short: "ZA", tier: "t5", zoneId: 3805 },
    { id: "hyjal", label: "Hyjalgipfel", short: "Hyjal", tier: "t6", zoneId: 3606 },
    { id: "bt", label: "Der Schwarze Tempel", short: "BT", tier: "t6", zoneId: 3959 },
    { id: "swp", label: "Sonnenbrunnenplateau", short: "SWP", tier: "t65", zoneId: 4075 },
];

// Instance names as the loot addons write them, so RCLootcouncil rows for items
// outside the table (trash, badge gear) still land in the right content.
// English and German client strings both appear in the wild — the German
// clients are what most of the guild plays, RCLootcouncil forwards whatever the
// client reported. Matched case-insensitively against the raw instance string,
// which usually looks like "Serpentshrine Cavern-25 Player".
const INSTANCE_PATTERNS = [
    { content: "kara", re: /karazhan/i },
    { content: "gruul", re: /gruul/i },
    { content: "mag", re: /magtheridon/i },
    { content: "ssc", re: /serpentshrine|schlangenschrein/i },
    { content: "tk", re: /tempest keep|the eye|festung der stürme|das auge/i },
    { content: "za", re: /zul'?aman/i },
    { content: "hyjal", re: /hyjal/i },
    { content: "bt", re: /black temple|schwarze[rn]? tempel/i },
    { content: "swp", re: /sunwell|sonnenbrunnen/i },
];

// >>> generated by scripts/fetch-tbc-loot.js — do not edit by hand
const RAID_LOOT = {
    kara: {
        "Attumen the Huntsman": [30480],
        "Hyakiss the Lurker": [30675, 30676, 30677, 30678],
        "Julianne": [28572, 28573, 28578, 28579],
        "Maiden of Virtue": [28511, 28512, 28514, 28515, 28516, 28517, 28518, 28519, 28520, 28521, 28522, 28523],
        "Moroes": [22559, 28524, 28525, 28528, 28529, 28530, 28545, 28565, 28566, 28567, 28568, 28569, 28570],
        "Netherspite": [28729, 28730, 28731, 28732, 28733, 28734, 28735, 28740, 28741, 28742, 28743, 28744],
        "Nightbane": [28597, 28599, 28600, 28601, 28602, 28603, 28604, 28606, 28608, 28609, 28610, 28611],
        "Phantom Attendant": [21903],
        "Phantom Stagehand": [22545],
        "Phantom Valet": [21904],
        "Prince Malchezaar": [28757, 28762, 28763, 28764, 28765, 28766, 28767, 28768, 28770, 28771, 28772, 28773, 29759, 29760, 29761],
        "Rokad the Ravager": [30684, 30685, 30686, 30687],
        "Shade of Aran": [22560, 28663, 28666, 28669, 28670, 28671, 28672, 28673, 28674, 28675, 28726, 28727, 28728],
        "Shadikith the Glider": [30680, 30681, 30682, 30683],
        "Terestian Illhoof": [22561, 28652, 28653, 28654, 28655, 28656, 28657, 28658, 28659, 28660, 28661, 28662, 28785],
        "The Big Bad Wolf": [28581, 28582, 28583, 28584],
        "The Crone": [28585, 28586, 28587, 28588],
        "The Curator": [28612, 28621, 28631, 28633, 28647, 28649, 29756, 29757, 29758],
        "": [23620, 23633, 23809, 28453, 28454, 28477, 28502, 28503, 28504, 28505, 28506, 28507, 28508, 28509, 28510, 28589, 28590, 28591, 28592, 28593, 28594, 30641, 30642, 30643, 30644, 30666, 30667, 30668, 30673, 30674],
    },
    gruul: {
        "Gruul the Dragonkiller": [28794, 28802, 28803, 28804, 28810, 28822, 28823, 28824, 28825, 28826, 28827, 28828, 28830, 29765, 29766, 29767],
        "High King Maulgar": [28795, 28796, 28797, 28799, 28800, 28801, 29762, 29763, 29764],
    },
    mag: {
        "Magtheridon": [191060],
        "": [28774, 28775, 28776, 28777, 28778, 28779, 28780, 28781, 28782, 28783, 28789, 29458, 29753, 29754, 29755, 32385, 32386, 34845, 34846],
    },
    ssc: {
        "Fathom-Lord Karathress": [30090, 30099, 30100, 30101, 30245, 30246, 30247, 30626, 30663],
        "Lady Vashj": [30102, 30103, 30104, 30105, 30106, 30107, 30108, 30109, 30110, 30111, 30112, 30242, 30243, 30244, 30621, 32895],
        "Morogrim Tidewalker": [30008, 30068, 30075, 30079, 30080, 30081, 30082, 30083, 30084, 30085, 30098, 30720, 33058],
        "The Lurker Below": [30057, 30058, 30059, 30060, 30061, 30062, 30063, 30064, 30065, 30066, 30067, 30665, 33054],
        "": [30021, 30022, 30023, 30025, 30027, 30047, 30048, 30049, 30050, 30051, 30052, 30053, 30054, 30055, 30056, 30091, 30092, 30095, 30096, 30097, 30239, 30240, 30241, 30620, 30627, 30629, 30664, 32516, 33055],
    },
    tk: {
        "Al'ar": [29918, 29920, 29921, 29922, 29923, 29924, 29925, 29947, 29948, 29949, 30447, 30448, 32944],
        "Cosmic Infuser": [30317],
        "Devastation": [30316],
        "High Astromancer Solarian": [29950, 29951, 29962, 29965, 29966, 29972, 29976, 29977, 29981, 29982, 30446, 30449, 32267],
        "Infinity Blades": [30312],
        "Kael'thas Sunstrider": [29987, 29988, 29989, 29990, 29991, 29992, 29993, 29994, 29995, 29996, 29997, 29998, 30236, 30237, 30238, 32405, 32458, 32896],
        "Netherstrand Longbow": [30318],
        "Phaseshift Bulwark": [30314],
        "Staff of Disintegration": [30313],
        "Void Reaver": [29983, 29984, 29985, 29986, 30248, 30249, 30250, 30450, 30619, 32515],
        "Warp Slicer": [30311],
        "": [30020, 30024, 30026, 30028, 30029, 30030],
    },
    za: {
        "Akil'zon": [33214, 33215, 33216, 33281, 33283, 33286, 33293],
        "Hex Lord Malacrass": [33298, 33388, 33389, 33421, 33432, 33446, 33453, 33463, 33464, 33465, 33592, 33828, 33829, 34029],
        "Jan'alai": [33326, 33328, 33329, 33332, 33354, 33356, 33357],
        "Nalorakk": [33191, 33203, 33206, 33211, 33285, 33327, 33640],
        "Zul'jin": [33102, 33466, 33467, 33468, 33469, 33471, 33473, 33474, 33476, 33478, 33479, 33830, 33831],
        "": [33297, 33299, 33300, 33303, 33307, 33317, 33322, 33533, 33865],
    },
    hyjal: {
        "Anetheron": [30874, 30878, 30879, 30880, 30881, 30882, 30883, 30884, 30885, 30886, 30887, 30888],
        "Archimonde": [30902, 30903, 30904, 30905, 30906, 30907, 30908, 30909, 30910, 30911, 30912, 30913, 31095, 31096, 31097],
        "Azgalor": [30896, 30897, 30898, 30899, 30900, 30901, 31092, 31093, 31094],
        "Kaz'rogal": [30889, 30891, 30892, 30893, 30894, 30895, 30914, 30915, 30916, 30917, 30918, 30919],
        "Rage Winterchill": [30861, 30862, 30863, 30864, 30865, 30866, 30868, 30869, 30870, 30871, 30872, 30873],
        "": [32285, 32289, 32295, 32296, 32297, 32298, 32303, 32307],
    },
    bt: {
        "Essence of Anger": [32332, 32345, 32346, 32347, 32349, 32350, 32351, 32352, 32353, 32354, 32362, 32363, 32517],
        "Gurtogg Bloodboil": [32269, 32333, 32334, 32335, 32337, 32338, 32339, 32340, 32341, 32342, 32343, 32344, 32501],
        "High Nethermancer Zerevor": [32331, 32373, 32376, 32505, 32518, 32519],
        "Illidan Stormrage": [31089, 31090, 31091, 32235, 32336, 32374, 32375, 32471, 32483, 32496, 32497, 32500, 32521, 32524, 32525, 32837, 32838],
        "Mother Shahraz": [31101, 31102, 31103, 32365, 32366, 32367, 32368, 32369, 32370],
        "Shade of Akama": [32263, 32264, 32265, 32266, 32268, 32270, 32271, 32273, 32275, 32276, 32278, 32279, 32361, 32513],
        "Supremus": [32250, 32251, 32252, 32253, 32254, 32255, 32256, 32257, 32258, 32259, 32260, 32261, 32262],
        "": [31098, 31099, 31100, 32232, 32234, 32236, 32237, 32238, 32239, 32240, 32241, 32242, 32243, 32245, 32247, 32248, 32377, 32428, 32526, 32527, 32528, 32593, 32606, 32608, 32943, 34011, 34012],
    },
    swp: {
        "Brutallus": [34176, 34177, 34178, 34179, 34180, 34181, 34853, 34854, 34855],
        "Felmyst": [34182, 34184, 34185, 34186, 34188, 34352, 34856, 34857, 34858],
        "Grand Warlock Alythess": [34189, 34190, 34192, 34193, 34194, 34195, 34196, 34197, 34198, 34199, 34202, 34203, 34204, 34205, 34206, 34208, 34209, 34210, 35290, 35291, 35292],
        "Kil'jaeden": [34241, 34242, 34243, 34244, 34245, 34247, 34329, 34331, 34332, 34333, 34334, 34335, 34336, 34337, 34339, 34340, 34341, 34342, 34343, 34344, 34345],
        "": [34164, 34165, 34166, 34167, 34168, 34169, 34170, 34183, 34211, 34212, 34213, 34214, 34215, 34216, 34228, 34229, 34230, 34231, 34232, 34233, 34234, 34240, 34346, 34347, 34348, 34349, 34350, 34351, 34427, 34428, 34429, 34430, 34664, 34848, 34851, 34852, 35186, 35187, 35189, 35190, 35191, 35192, 35193, 35194, 35195, 35196, 35197, 35198, 35199, 35200, 35201, 35202, 35203, 35204, 35205, 35206, 35207, 35208, 35209, 35210, 35211, 35212, 35213, 35214, 35215, 35216, 35217, 35218, 35219, 35273, 35282, 35283, 35284, 35733],
    },
};
// <<< end generated

// item id → { content, boss } and content id → meta, both built once at require
// time. RAID_LOOT is keyed the other way round because that is the shape the
// generator can write readably; every lookup wants the reverse.
const ITEM_SOURCE = new Map();
for (const [content, byBoss] of Object.entries(RAID_LOOT)) {
    for (const [boss, ids] of Object.entries(byBoss)) {
        for (const id of ids) ITEM_SOURCE.set(id, { content, boss });
    }
}
const CONTENT_BY_ID = new Map(CONTENTS.map((c) => [c.id, c]));
const TIER_BY_ID = new Map(TIERS.map((t) => [t.id, t]));

/** The content meta for an id, or null. */
function content(contentId) {
    return CONTENT_BY_ID.get(String(contentId || "")) || null;
}

/** What the generated table knows about an item id: { content, boss } or null. */
function sourceForItem(itemId) {
    const id = Number(itemId) || 0;
    return id ? (ITEM_SOURCE.get(id) || null) : null;
}

/** The content id an instance string names, or "". */
function contentForInstance(instance) {
    const s = String(instance || "").trim();
    if (!s) return "";
    const hit = INSTANCE_PATTERNS.find((p) => p.re.test(s));
    return hit ? hit.content : "";
}

/**
 * Where a loot row came from: the item table first (works for every source,
 * including Gargul's id-only rows), the export's instance string second.
 * Returns { contentId, boss } with "" for whatever could not be resolved —
 * unknown items are shown as such rather than guessed into a raid.
 */
function contentForLoot(item) {
    const it = item || {};
    const known = sourceForItem(it.itemId);
    const contentId = known ? known.content : contentForInstance(it.instance);
    return { contentId, boss: String(it.boss || "").trim() || (known ? known.boss : "") };
}

// The tier tokens ("Chestguard of the Fallen Champion", "Helm der siegreichen
// …") are what actually drops — the set piece itself is traded from a vendor
// and never shows up in a loot export. Matching the token lets the item list
// answer "who got tier?" without a second table. The three token adjectives are
// one per tier: Fallen = T4, Vanquished = T5, Forgotten = T6 (Sunwell's
// Sunmote-upgraded pieces reuse the T6 tokens).
const TOKEN_TIERS = [
    { tier: "t4", re: /\bfallen\b|\bgefallen/i },
    { tier: "t5", re: /\bvanquished\b|besiegt/i },
    { tier: "t6", re: /\bforgotten\b|vergessen/i },
];
const TOKEN_CLASSES = /champion|defender|hero|conqueror|protector|vanquisher|verteidiger|held|eroberer|beschützer|bezwinger/i;

/**
 * The tier a set token belongs to ("t4"/"t5"/"t6"), or "" for anything that is
 * not a token. Name-based, because that is all a loot row carries; both the
 * English and the German item names are matched.
 */
function tokenTier(itemName) {
    const name = String(itemName || "");
    if (!name || !TOKEN_CLASSES.test(name)) return "";
    const hit = TOKEN_TIERS.find((t) => t.re.test(name));
    return hit ? hit.tier : "";
}

module.exports = {
    TIERS, CONTENTS, RAID_LOOT,
    content, sourceForItem, contentForInstance, contentForLoot, tokenTier,
    tier: (id) => TIER_BY_ID.get(String(id || "")) || null,
};
