// The defaults of the raid plan catalog (docs/raidplan.md): mobs (adds, council members, trash) and the spells that
// are handed out as assignments. They are code, not data: the admin can override, hide or extend them in
// "Raidplan-Katalog" and reset an entry to its default — no migration ever touches them.
//
// Only what is certain is in here. Names are the TBC (Classic Anniversary) names from Wowhead TBC / the Warcraft
// Wiki (warcraft.wiki.gg: the encounter pages of Black Temple, Hyjal Summit, Karazhan, Serpentshrine Cavern,
// Tempest Keep and the Sunwell Plateau; the spell pages of the classes). What is not sure is left out and can be
// added by the admin. A mob's `icon` is a similar icon of the Wowhead icon CDN (see below, `similar: true`); the admin
// can set any icon name or a boss icon (`boss:<encounter id>`).
//
// A mob: { id, name, kind: boss | add | trash | other, instanceId, bossKey ("" = none, else "<instance>/<boss slug>"), icon, note, versions }
// A spell: { id, name, nameEn, icon, type (an assignment type), classes: [class ids], note, versions }
// `versions` (#544) names the game versions that have the entry ("tbc", "classic", "forever", "wotlk" ...): a plan only offers the
// entries of its own version, so a plan of a TBC raid never offers Tricks of the Trade (Patch 3.0.2, Wrath of the Lich King) and a Forever
// plan none of the TBC mobs and spells. EVERY default carries it (the audit test fails on one without). Everything here is ["tbc"]: the
// mobs are adds and trash of TBC raids; the spells are the TBC ranks and talents checked against Wowhead TBC - whether Classic or Forever
// have the same spell under the same name is not checked (Classic's mage has "Remove Lesser Curse"; Bloodlust, Heroism and Misdirection
// are new in TBC), so another version is left to the admin (the catalog's version chips) until the class data of that version is
// verified. Every default is checked against SINCE in test/services/raidplan/raidplanCatalogAudit.test.js.

// The icons come from src/config/generated/mobIcons.json, generated by scripts/fetch-mob-icons.js (similar WoW icons by kind of
// creature, every one checked against the icon CDN; docs/raidplan.md), and, for most mobs, a real portrait (`mob:<NPC id>`,
// the model render of the NPC, public/mobs/<id>.png). `similar` marks the mobs that only have a placeholder icon.
let MOB_ICONS = {};
let MOB_PORTRAITS = {};
try {
    const generated = require("../../config/generated/mobIcons.json");
    MOB_ICONS = generated.icons || {};
    MOB_PORTRAITS = generated.portraits || {};
} catch { /* not generated yet: the mobs have no icon */ }

const mob = (slug, name, kind, instanceId, bossKey = "") => ({
    id: `d:${slug}`, name, kind, instanceId, bossKey, icon: (MOB_PORTRAITS[`d:${slug}`] || MOB_ICONS[`d:${slug}`] || {}).icon || "", similar: !MOB_PORTRAITS[`d:${slug}`] && !!MOB_ICONS[`d:${slug}`], note: "", versions: ["tbc"],
});

const MOBS = [
    // Black Temple
    mob("gathios", "Gathios the Shatterer", "add", "bt", "bt/the-illidari-council"),
    mob("zerevor", "High Nethermancer Zerevor", "add", "bt", "bt/the-illidari-council"),
    mob("malande", "Lady Malande", "add", "bt", "bt/the-illidari-council"),
    mob("veras", "Veras Darkshadow", "add", "bt", "bt/the-illidari-council"),
    mob("flame-of-azzinoth", "Flame of Azzinoth", "add", "bt", "bt/illidan-stormrage"),
    mob("shadow-demon", "Shadow Demon", "add", "bt", "bt/illidan-stormrage"),
    mob("parasitic-shadowfiend", "Parasitic Shadowfiend", "add", "bt", "bt/illidan-stormrage"),
    mob("maiev", "Maiev Shadowsong", "add", "bt", "bt/illidan-stormrage"),
    mob("ashtongue-channeler", "Ashtongue Channeler", "add", "bt", "bt/shade-of-akama"),
    mob("ashtongue-sorcerer", "Ashtongue Sorcerer", "add", "bt", "bt/shade-of-akama"),
    mob("ashtongue-defender", "Ashtongue Defender", "add", "bt", "bt/shade-of-akama"),
    mob("ashtongue-elementalist", "Ashtongue Elementalist", "add", "bt", "bt/shade-of-akama"),
    mob("ashtongue-rogue", "Ashtongue Rogue", "add", "bt", "bt/shade-of-akama"),
    mob("essence-of-suffering", "Essence of Suffering", "add", "bt", "bt/reliquary-of-the-lost"),
    mob("essence-of-desire", "Essence of Desire", "add", "bt", "bt/reliquary-of-the-lost"),
    mob("essence-of-anger", "Essence of Anger", "add", "bt", "bt/reliquary-of-the-lost"),
    mob("shadowy-construct", "Shadowy Construct", "add", "bt", "bt/teron-gorefiend"),
    mob("vengeful-spirit", "Vengeful Spirit", "add", "bt", "bt/teron-gorefiend"),
    mob("illidari-nightlord", "Illidari Nightlord", "trash", "bt"),
    mob("illidari-fearbringer", "Illidari Fearbringer", "trash", "bt"),
    mob("illidari-defiler", "Illidari Defiler", "trash", "bt"),
    mob("illidari-heartseeker", "Illidari Heartseeker", "trash", "bt"),
    // Hyjal Summit
    mob("towering-infernal", "Towering Infernal", "add", "hyjal", "hyjal/anetheron"),
    mob("lesser-doomguard", "Lesser Doomguard", "add", "hyjal", "hyjal/azgalor"),
    mob("doomfire-spirit", "Doomfire Spirit", "add", "hyjal", "hyjal/archimonde"),
    mob("hyjal-abomination", "Abomination", "trash", "hyjal"),
    mob("hyjal-ghoul", "Ghoul", "trash", "hyjal"),
    mob("hyjal-necromancer", "Necromancer", "trash", "hyjal"),
    mob("hyjal-crypt-fiend", "Crypt Fiend", "trash", "hyjal"),
    mob("hyjal-giant-infernal", "Giant Infernal", "trash", "hyjal"),
    // Karazhan
    mob("midnight", "Midnight", "add", "kara", "kara/attumen-the-huntsman"),
    mob("netherspite-infernal", "Netherspite Infernal", "add", "kara", "kara/prince-malchezaar"),
    // Serpentshrine Cavern
    mob("pure-spawn", "Pure Spawn of Hydross", "add", "ssc", "ssc/hydross-the-unstable"),
    mob("tainted-spawn", "Tainted Spawn of Hydross", "add", "ssc", "ssc/hydross-the-unstable"),
    mob("fathom-guard-sharkkis", "Fathom-Guard Sharkkis", "add", "ssc", "ssc/fathom-lord-karathress"),
    mob("fathom-guard-tidalvess", "Fathom-Guard Tidalvess", "add", "ssc", "ssc/fathom-lord-karathress"),
    mob("fathom-guard-caribdis", "Fathom-Guard Caribdis", "add", "ssc", "ssc/fathom-lord-karathress"),
    mob("tainted-elemental", "Tainted Elemental", "add", "ssc", "ssc/lady-vashj"),
    mob("coilfang-strider", "Coilfang Strider", "add", "ssc", "ssc/lady-vashj"),
    mob("enchanted-elemental", "Enchanted Elemental", "add", "ssc", "ssc/lady-vashj"),
    // Tempest Keep: The Eye
    mob("thaladred", "Thaladred the Darkener", "add", "tk", "tk/kaelthas-sunstrider"),
    mob("sanguinar", "Lord Sanguinar", "add", "tk", "tk/kaelthas-sunstrider"),
    mob("capernian", "Grand Astromancer Capernian", "add", "tk", "tk/kaelthas-sunstrider"),
    mob("telonicus", "Master Engineer Telonicus", "add", "tk", "tk/kaelthas-sunstrider"),
    // Sunwell Plateau
    mob("sathrovarr", "Sathrovarr the Corruptor", "add", "swp", "swp/kalecgos"),
    mob("void-sentinel", "Void Sentinel", "add", "swp", "swp/muru"),
];

const spell = (slug, name, icon, type, classes, nameEn = "", versions = ["tbc"]) => ({ id: `d:${slug}`, name, nameEn, icon, type, classes, note: "", versions });

const SPELLS = [
    spell("curse-of-the-elements", "Curse of the Elements", "spell_shadow_chilltouch", "curse", ["Warlock"]),
    spell("curse-of-recklessness", "Curse of Recklessness", "spell_shadow_unholystrength", "curse", ["Warlock"]),
    spell("curse-of-doom", "Curse of Doom", "spell_shadow_auraofdarkness", "curse", ["Warlock"]),
    spell("curse-of-agony", "Curse of Agony", "spell_shadow_curseofsargeras", "curse", ["Warlock"]),
    spell("curse-of-tongues", "Curse of Tongues", "spell_shadow_curseoftounges", "curse", ["Warlock"]),
    spell("curse-of-weakness", "Curse of Weakness", "spell_shadow_curseofmannoroth", "curse", ["Warlock"]),
    spell("thunder-clap", "Thunder Clap", "spell_nature_thunderclap", "thunderclap", ["Warrior"], "Thunder Clap"),
    spell("demoralizing-shout", "Demoralizing Shout", "ability_warrior_warcry", "demoshout", ["Warrior"]),
    spell("misdirection", "Misdirection", "ability_hunter_misdirection", "md", ["Hunter"]),
    // Wrath of the Lich King (Patch 3.0.2): not in The Burning Crusade, where only hunters misdirect
    spell("tricks-of-the-trade", "Tricks of the Trade", "ability_rogue_tricksofthetrade", "md", ["Rogue"], "", ["wotlk"]),
    spell("soulstone","Soulstone Resurrection", "spell_shadow_soulgem", "ss", ["Warlock"]),
    spell("fear-ward", "Fear Ward", "spell_holy_excorcism", "fearward", ["Priest"]),
    spell("kick", "Kick", "ability_kick", "kick", ["Rogue"]),
    spell("pummel", "Pummel", "inv_gauntlets_04", "kick", ["Warrior"]),
    spell("shield-bash", "Shield Bash", "ability_warrior_shieldbash", "kick", ["Warrior"]),
    spell("earth-shock", "Earth Shock", "spell_nature_earthshock", "kick", ["Shaman"]),
    spell("counterspell", "Counterspell", "spell_frost_iceshock", "kick", ["Mage"]),
    spell("dispel-magic", "Dispel Magic", "spell_holy_dispelmagic", "dispel", ["Priest"]),
    spell("cleanse", "Cleanse", "spell_holy_renew", "dispel", ["Paladin"]),
    spell("purge", "Purge", "spell_nature_purge", "dispel", ["Shaman"]),
    spell("remove-curse", "Remove Curse", "spell_nature_removecurse", "dispel", ["Mage", "Druid"]),
    spell("cure-poison", "Cure Poison", "spell_nature_nullifypoison", "dispel", ["Druid", "Shaman"]),
    spell("innervate", "Innervate", "spell_nature_lightning", "buff", ["Druid"]),
    // faction spells (Warcraft Wiki: Bloodlust Horde, Heroism Alliance; same effect): named with their faction so the plan says which shaman it means
    spell("bloodlust", "Bloodlust (Horde)", "spell_nature_bloodlust", "buff", ["Shaman"], "Bloodlust (Horde)"),
    spell("heroism", "Heroism (Alliance)", "spell_holy_heroism", "buff", ["Shaman"], "Heroism (Alliance)"),
    spell("power-infusion", "Power Infusion", "spell_holy_powerinfusion", "buff", ["Priest"]),
    spell("shackle-undead", "Shackle Undead", "spell_nature_slow", "cc", ["Priest"]),
    spell("polymorph", "Polymorph", "spell_nature_polymorph", "cc", ["Mage"]),
    spell("hibernate", "Hibernate", "spell_nature_sleep", "cc", ["Druid"]),
    spell("banish", "Banish", "spell_shadow_cripple", "cc", ["Warlock"]),
    spell("taunt", "Taunt", "spell_nature_reincarnation", "tank", ["Warrior"]),
    spell("growl", "Growl", "ability_physical_taunt", "tank", ["Druid"]),
    // #536, the raid-wide tasks of the "Allgemein" section. Name and icon of every entry checked against the Wowhead TBC spell (the tooltip of
    // wowhead.com/tbc/spell=<id>, the id given per line), the icon also against the icon CDN (HTTP 200). All exist in 2.4.3.
    // Buffs (raid / party buffs someone has to cast; the cooldowns Innervate, Bloodlust, Heroism, Power Infusion are above)
    spell("battle-shout", "Battle Shout", "ability_warrior_battleshout", "buff", ["Warrior"]), // 2048
    spell("commanding-shout", "Commanding Shout", "ability_warrior_rallyingcry", "buff", ["Warrior"]), // 469 (new in TBC)
    spell("prayer-of-fortitude", "Prayer of Fortitude", "spell_holy_prayeroffortitude", "buff", ["Priest"]), // 25392
    spell("prayer-of-spirit", "Prayer of Spirit", "spell_holy_prayerofspirit", "buff", ["Priest"]), // 32999 (Divine Spirit talent)
    spell("prayer-of-shadow-protection", "Prayer of Shadow Protection", "spell_holy_prayerofshadowprotection", "buff", ["Priest"]), // 39374
    spell("arcane-brilliance", "Arcane Brilliance", "spell_holy_arcaneintellect", "buff", ["Mage"]), // 27127
    spell("gift-of-the-wild", "Gift of the Wild", "spell_nature_giftofthewild", "buff", ["Druid"]), // 26991
    // Blessings (paladin; one entry each, the Greater Blessing of the same name is the same assignment): Kings 20217 / 25898, Might 27140 / 27141,
    // Wisdom 27142 / 27143, Salvation 1038 / 25895, Light 27144 / 27145, Sanctuary 27168 / 27169 (Kings and Sanctuary are talents)
    spell("blessing-of-kings", "Blessing of Kings", "spell_magic_magearmor", "blessing", ["Paladin"]),
    spell("blessing-of-might", "Blessing of Might", "spell_holy_fistofjustice", "blessing", ["Paladin"]),
    spell("blessing-of-wisdom", "Blessing of Wisdom", "spell_holy_sealofwisdom", "blessing", ["Paladin"]),
    spell("blessing-of-salvation", "Blessing of Salvation", "spell_holy_sealofsalvation", "blessing", ["Paladin"]),
    spell("blessing-of-light", "Blessing of Light", "spell_holy_prayerofhealing02", "blessing", ["Paladin"]),
    spell("blessing-of-sanctuary", "Blessing of Sanctuary", "spell_nature_lightningshield", "blessing", ["Paladin"]),
    // Auras (party-wide in TBC, so they are handed out per group): the paladin auras, and the passive auras of a spec (Trueshot Aura, Leader of
    // the Pack, Moonkin Aura, Tree of Life) - those are only a group placement, the suggestion never hands them out
    spell("devotion-aura", "Devotion Aura", "spell_holy_devotionaura", "aura", ["Paladin"]), // 27149
    spell("retribution-aura", "Retribution Aura", "spell_holy_auraoflight", "aura", ["Paladin"]), // 27150
    spell("concentration-aura", "Concentration Aura", "spell_holy_mindsooth", "aura", ["Paladin"]), // 19746
    spell("shadow-resistance-aura", "Shadow Resistance Aura", "spell_shadow_sealofkings", "aura", ["Paladin"]), // 27151
    spell("frost-resistance-aura", "Frost Resistance Aura", "spell_frost_wizardmark", "aura", ["Paladin"]), // 27152
    spell("fire-resistance-aura", "Fire Resistance Aura", "spell_fire_sealoffire", "aura", ["Paladin"]), // 27153
    spell("trueshot-aura", "Trueshot Aura", "ability_trueshot", "aura", ["Hunter"]), // 27066 (Marksmanship talent)
    spell("leader-of-the-pack", "Leader of the Pack", "spell_nature_unyeildingstamina", "aura", ["Druid"]), // 17007 (Feral talent)
    spell("moonkin-aura", "Moonkin Aura", "spell_nature_moonglow", "aura", ["Druid"]), // 24907 (Moonkin Form)
    spell("tree-of-life", "Tree of Life", "ability_druid_treeoflife", "aura", ["Druid"]), // 33891 (new in TBC, Restoration talent)
    // Totems (shaman, party-wide: one row per shaman and group)
    spell("windfury-totem", "Windfury Totem", "spell_nature_windfury", "totem", ["Shaman"]), // 25587
    spell("grace-of-air-totem", "Grace of Air Totem", "spell_nature_invisibilitytotem", "totem", ["Shaman"]), // 25359
    spell("wrath-of-air-totem", "Wrath of Air Totem", "spell_nature_slowingtotem", "totem", ["Shaman"]), // 3738 (new in TBC)
    spell("tranquil-air-totem", "Tranquil Air Totem", "spell_nature_brilliance", "totem", ["Shaman"]), // 25908
    spell("strength-of-earth-totem", "Strength of Earth Totem", "spell_nature_earthbindtotem", "totem", ["Shaman"]), // 25528
    spell("mana-spring-totem", "Mana Spring Totem", "spell_nature_manaregentotem", "totem", ["Shaman"]), // 25570
    spell("mana-tide-totem", "Mana Tide Totem", "spell_frost_summonwaterelemental", "totem", ["Shaman"]), // 16190 (Restoration talent)
    spell("totem-of-wrath", "Totem of Wrath", "spell_fire_totemofwrath", "totem", ["Shaman"]), // 30706 (new in TBC, Elemental talent)
    spell("tremor-totem", "Tremor Totem", "spell_nature_tremortotem", "totem", ["Shaman"]), // 8143
    spell("fire-resistance-totem", "Fire Resistance Totem", "spell_fireresistancetotem_01", "totem", ["Shaman"]), // 25563
    spell("frost-resistance-totem", "Frost Resistance Totem", "spell_frostresistancetotem_01", "totem", ["Shaman"]), // 25560
    spell("nature-resistance-totem", "Nature Resistance Totem", "spell_nature_natureresistancetotem", "totem", ["Shaman"]), // 25574
    // Debuffs on the boss (armour, spell vulnerability, attack power, the paladin judgements; Curse of Recklessness stays with the curses)
    spell("sunder-armor", "Sunder Armor", "ability_warrior_sunder", "debuff", ["Warrior"]), // 25225
    spell("expose-armor", "Expose Armor", "ability_warrior_riposte", "debuff", ["Rogue"]), // 26866 (does not stack with Sunder Armor)
    spell("faerie-fire", "Faerie Fire", "spell_nature_faeriefire", "debuff", ["Druid"]), // 26993 (Faerie Fire (Feral) is the same debuff)
    spell("hunters-mark", "Hunter's Mark", "ability_hunter_snipershot", "debuff", ["Hunter"]), // 14325
    spell("improved-scorch", "Improved Scorch", "spell_fire_soulburn", "debuff", ["Mage"]), // 12873 (Fire talent: Scorch 27074 stacks Fire Vulnerability)
    spell("shadow-weaving", "Shadow Weaving", "spell_shadow_blackplague", "debuff", ["Priest"]), // 15334 (Shadow talent)
    spell("misery", "Misery", "spell_shadow_misery", "debuff", ["Priest"]), // 33195 (new in TBC, Shadow talent)
    spell("judgement-of-wisdom", "Judgement of Wisdom", "spell_holy_righteousnessaura", "debuff", ["Paladin"]), // 20355
    spell("judgement-of-light", "Judgement of Light", "spell_holy_healingaura", "debuff", ["Paladin"]), // 27163
    spell("judgement-of-the-crusader", "Judgement of the Crusader", "spell_holy_holysmite", "debuff", ["Paladin"]), // 27159
    // Battle res
    spell("rebirth", "Rebirth", "spell_nature_reincarnation", "brez", ["Druid"]), // 26994
];

/**
 * When each default spell first exists (the game version that introduced it), from the Warcraft Wiki / Wowhead TBC spell pages: Fear Ward became a spell of
 * ALL priests in Patch 2.3.0 (before: Draenei and Dwarf only), Tricks of the Trade is Patch 3.0.2 (Wrath). The audit test fails when a spell that exists later
 * than TBC is not limited to its versions.
 */
// Checked one by one against Wowhead TBC / Warcraft Wiki (all exist in 2.4.3): Shield Bash (warrior, needs a shield: wowclassicdb.com/tbc/spell/36988),
// Cure Poison for druids AND shamans (wowhead.com/tbc/spell=526), Remove Curse for mages AND druids (wowhead.com/tbc/spell=2782), Fear Ward (all priests since 2.3.0),
// Bloodlust (Horde) / Heroism (Alliance). Nothing to remove.
// #536 (Sept 2026): left out on purpose - Expose Weakness (34503, a passive Survival proc, nobody to assign), Improved Hunter's Mark (a talent of
// Hunter's Mark), Sanctity Aura and Crusader Aura (passive / not a raid aura), the resistance totems' and auras' later ranks (one entry each).
// The entries new in TBC are named here with "tbc" for the record; like every entry up to TBC they carry `versions: ["tbc"]`; what came
// after TBC carries its own version only.
const SINCE = {
    "tricks-of-the-trade": "wotlk",
    "commanding-shout": "tbc", "wrath-of-air-totem": "tbc", "totem-of-wrath": "tbc", "misery": "tbc", "tree-of-life": "tbc",
};

module.exports = { MOBS, SPELLS, SINCE };
