// German bot texts of the guild bank (the organizer's area, the request modal, the raider's answer and DM).
module.exports = {
    // the organizer (utils/signup/organizerPanel.js)
    "Guild bank": "Gildenbank",
    "Request mats, potions or enchants – the orga will get back to you by DM": "Mats, Tränke oder Verzauberungen anfragen – die Orga meldet sich per DM",
    "Make a request": "Anfrage stellen",
    // the modal (utils/signup/guildBankPost.js)
    "Guild bank request": "Gildenbank-Anfrage",
    "What do you need?": "Was brauchst du?",
    "e.g. Super Mana Potion": "z. B. Super-Manatrank",
    "How many?": "Wie viel?",
    "e.g. 10": "z. B. 10",
    "What for? (optional)": "Wofür? (optional)",
    "e.g. Black Temple on Thursday": "z. B. Black Temple am Donnerstag",
    // the request form from the stock (utils/signup/guildBankPick.js)
    "Bank as of: {when}.": "Stand der Bank: {when}.",
    "You only see what the orga has released.": "Du siehst nur, was die Orga freigegeben hat.",
    "Next the bot asks for the amount and what it is for.": "Danach fragt der Bot nach Menge und Zweck.",
    "{count} more categories are not shown.": "{count} weitere Kategorien werden nicht angezeigt.",
    "1 kind": "1 Sorte",
    "{count} kinds": "{count} Sorten",
    "{count} shown": "{count} angezeigt",
    "Other": "Sonstiges",
    "Pick an item …": "Gegenstand wählen …",
    "Available: {count}": "Verfügbar: {count}",
    "max. {count} per request": "max. {count} pro Anfrage",
    "max. {count}": "max. {count}",
    "e.g. 2": "z. B. 2",
    "To which character?": "An welchen Charakter?",
    // the answer and the DM
    "Request sent – the orga will get back to you by DM.": "Anfrage gesendet – die Orga meldet sich per DM.",
    "For: {purpose}": "Wofür: {purpose}",
    "To: {character}": "An: {character}",
    "The guild bank is not set up right now.": "Die Gildenbank ist gerade nicht eingerichtet.",
    "Request done": "Anfrage erledigt",
    "Request declined": "Anfrage abgelehnt",
    "Request confirmed": "Anfrage bestätigt",
    "Set aside for you – you will get it in game soon.": "Für dich vorgemerkt – du bekommst es bald im Spiel.",
    "Request handed out": "Anfrage ausgegeben",
    "Handed out to {character}.": "An {character} ausgegeben.",
    "Sent by mail to {character}.": "Per Post an {character} geschickt.",
    "Sent by mail.": "Per Post geschickt.",
};
