// German bot texts of the signup flows in Discord (event message buttons and
// selects, the signup dialog, the character select, several raids at once, the
// talk overview's select), /profil, the access refusal and the note post.
module.exports = {
    // shared answers
    "This event no longer exists.": "Dieses Event gibt es nicht mehr.",
    "The event was cancelled.": "Das Event wurde abgesagt.",
    "The event was cancelled – {reason}.": "Das Event wurde abgesagt – {reason}.",
    "The raid has already started – signups are closed.": "Der Raid hat schon begonnen – Anmeldungen sind geschlossen.",
    "Signups are closed – you can only sign off now.": "Die Anmeldung ist geschlossen – du kannst dich nur noch abmelden.",
    "The signup deadline has passed – only “Late” or Absence now.": "Der Anmeldeschluss ist vorbei – nur noch „Spät“ oder Absagen.",
    "The signup deadline has passed – only Absence or “Late” now.": "Der Anmeldeschluss ist vorbei – nur noch Abmelden oder „Spät“.",
    "The signup deadline has passed – you can only sign off or sign up as “Late” now.":
        "Der Anmeldeschluss ist vorbei – du kannst dich nur noch abmelden oder „Spät“ angeben.",
    "Unknown status.": "Unbekannter Status.",
    "Unknown class.": "Unbekannte Klasse.",
    "Unknown spec.": "Unbekannte Spec.",
    "This raid is archived": "Dieser Raid ist archiviert",
    "{version} is no longer shown in EventHelper, so signups and changes are closed. Nothing was deleted.":
        "{version} wird im EventHelper nicht mehr angezeigt, deshalb sind Anmeldungen und Änderungen geschlossen. Gelöscht wurde nichts.",
    // gear, roles, "kann auch"
    "raid ready": "raidbereit",
    "usable": "brauchbar",
    "no gear": "kein Gear",
    "gear usable": "Gear brauchbar",
    "gear raid ready": "Gear raidbereit",
    "Tank": "Tank",
    "Healer": "Heiler",
    "Off-tank": "Offtank",
    "Heal": "Heilen",
    "Melee (off-spec)": "Nahkampf (Zweitspec)",
    "Ranged (off-spec)": "Fernkampf (Zweitspec)",
    // signup dialog
    "No {version} character in your profile yet – create a {version} character in your [profile]({url}) or pick class and spec here.":
        "Noch kein {version}-Charakter in deinem Profil – leg einen {version}-Charakter in deinem [Profil]({url}) an oder wähle hier Klasse und Spec.",
    "Your status: **{status}**": "Dein Status: **{status}**",
    "No character in your profile yet – pick class and spec here or [create a profile]({url}).":
        "Noch kein Charakter in deinem Profil – wähle hier Klasse und Spec oder [leg ein Profil an]({url}).",
    "Also signed up: {names}": "Ebenfalls angemeldet: {names}",
    "Pick character · spec …": "Charakter · Spec wählen …",
    "Pick a class …": "Klasse wählen …",
    "Pick a spec …": "Spec wählen …",
    "Can also … (heal, off-tank, off-spec)": "Kann auch … (heilen, Offtank, Zweitspec)",
    "Comment": "Kommentar",
    "Open on the web": "Im Web öffnen",
    "Add a {version} character": "{version}-Charakter anlegen",
    "Create profile": "Profil anlegen",
    "Signed off.": "Abgemeldet.",
    "Saved: **{status}**": "Gespeichert: **{status}**",
    "Your character's name": "Name deines Charakters",
    "Your character's name ({class})": "Name deines Charakters ({class})",
    "First name Last name – at most {max} letters each": "Vorname Nachname – je höchstens {max} Buchstaben",
    "At most {max} letters": "Höchstens {max} Buchstaben",
    "Add a character": "Charakter hinzufügen",
    "Comment on your signup": "Kommentar zu deiner Anmeldung",
    "e.g. joining 15 minutes late": "z. B. komme 15 Minuten später",
    "Sign up first – then you can leave a comment.": "Melde dich zuerst an – dann kannst du einen Kommentar hinterlassen.",
    "Comment saved.": "Kommentar gespeichert.",
    "Comment removed.": "Kommentar entfernt.",
    "Please pick class and spec first.": "Bitte zuerst Klasse und Spec wählen.",
    "Please pick character and spec first.": "Bitte zuerst Charakter und Spec wählen.",
    // the buttons and selects under the event message
    "Signed off from **{title}**": "Abgemeldet von **{title}**",
    "Signed off from **{title}** – reason: {reason}": "Abgemeldet von **{title}** – Grund: {reason}",
    "Signed off from {title}": "Abgemeldet von {title}",
    "Saved for **{title}**": "Gespeichert für **{title}**",
    "You are already signed up with {max} characters – pick again under “My characters …”.":
        "Du bist schon mit {max} Charakteren angemeldet – wähle unter „Meine Charaktere …“ neu.",
    "Sign up": "Anmelden",
    "as **{status}**": "als **{status}**",
    "So far: {list}": "Bisher: {list}",
    "Pick up to {max} characters – the topmost in the list is your 1st choice.": "Wähle bis zu {max} Charaktere – der oberste in der Liste ist deine 1. Wahl.",
    "Pick your character.": "Wähle deinen Charakter.",
    "Choose all Characters to sign up with": "Alle Charaktere wählen, mit denen du dich anmeldest",
    "Or a new character: pick a class …": "Oder ein neuer Charakter: Klasse wählen …",
    "Which class?": "Welche Klasse?",
    "**{class}** – which spec?": "**{class}** – welche Spec?",
    "Other class": "Andere Klasse",
    "Message to the raid lead": "Nachricht an die Raidleitung",
    "Message to the raid lead (optional)": "Nachricht an die Raidleitung (optional)",
    "e.g. work, holiday, sick": "z. B. Arbeit, Urlaub, krank",
    "e.g. not sure yet, might be late": "z. B. noch unsicher, komme evtl. später",
    "Sign off": "Abmelden",
    "Tentative": "Vielleicht",
    "Please leave a short message.": "Bitte hinterlass eine kurze Nachricht.",
    "No character in your profile yet – pick class and spec, then the bot asks for the name.":
        "Noch kein Charakter in deinem Profil – wähle Klasse und Spec, dann fragt der Bot nach dem Namen.",
    "No character in your profile yet – which class are you coming with as “{status}”?":
        "Noch kein Charakter in deinem Profil – mit welcher Klasse kommst du als „{status}“?",
    "No character picked.": "Kein Charakter gewählt.",
    "Unknown spec – please pick again.": "Unbekannte Spec – bitte neu wählen.",
    "{name} is already in your profile as a {class} – pick another name.": "{name} steht schon als {class} in deinem Profil – wähle einen anderen Namen.",
    "Pick class and spec, then click “{label}” – the bot then asks for your character's name.":
        "Wähle Klasse und Spec und klick dann auf „{label}“ – der Bot fragt dann nach dem Namen deines Charakters.",
    // the character select ("Anmelden …")
    "Which character? – from your EventHelper profile": "Welcher Charakter? – aus deinem EventHelper-Profil",
    "So far: **{status}**": "Bisher: **{status}**",
    "last used": "zuletzt genutzt",
    "Save: {status}": "Speichern: {status}",
    "Can also …": "Kann auch …",
    "Several characters …": "Mehrere Charaktere …",
    "Profile": "Profil",
    // several raids at once
    "Raid {n}": "Raid {n}",
    "Raids {from}–{to}": "Raids {from}–{to}",
    "Step 1 of 2 · only visible to you": "Schritt 1 von 2 · nur für dich sichtbar",
    "Pick the raids you want to join. Next you pick your characters per raid.":
        "Wähle die Raids, bei denen du dabei sein willst. Danach wählst du deine Charaktere je Raid.",
    "All coming raids are selected – remove what does not suit you. Next you pick your characters per raid.":
        "Alle kommenden Raids sind gewählt – nimm raus, was dir nicht passt. Danach wählst du deine Charaktere je Raid.",
    "{count} raids per window – after submitting, “Next” takes you to the following ones.":
        "{count} Raids pro Fenster – nach dem Absenden bringt dich „Weiter“ zu den nächsten.",
    "Which raids?": "Welche Raids?",
    "Pick raids …": "Raids wählen …",
    "Status for all": "Status für alle",
    "Next: characters ({range})": "Weiter: Charaktere ({range})",
    "Next: characters": "Weiter: Charaktere",
    "Topmost pick = 1st choice, the others = “can also come with”": "Oberste Wahl = 1. Wahl, die anderen = „kann auch mit“",
    "Sign up for all {count} raids": "Für alle {count} Raids anmelden",
    "Characters · specs for all raids": "Charaktere · Specs für alle Raids",
    "What does not fit a raid is skipped.": "Was nicht zu einem Raid passt, wird übersprungen.",
    "empty = skip": "leer = überspringen",
    "Which characters?": "Welche Charaktere?",
    "{character} skipped: {reason}": "{character} übersprungen: {reason}",
    "Waiting list (bench)": "Warteliste (Bank)",
    "signed off": "abgemeldet",
    "skipped (no character picked)": "übersprungen (kein Charakter gewählt)",
    "not saved": "nicht gespeichert",
    "Signup: {saved} of {total} raids saved": "Anmeldung: {saved} von {total} Raids gespeichert",
    "So far {saved} of {total} raids saved": "Bisher {saved} von {total} Raids gespeichert",
    "Next: {range}": "Weiter: {range}",
    "My signups": "Meine Anmeldungen",
    "Nothing picked.": "Nichts gewählt.",
    "This selection has expired – start the signup again from the raid overview.":
        "Diese Auswahl ist abgelaufen – starte die Anmeldung neu über die Raid-Übersicht.",
    "Your profile has no character with a spec yet – add one first (My profile).":
        "Dein Profil hat noch keinen Charakter mit Spec – leg zuerst einen an (Mein Profil).",
    "To sign up for several raids you need characters with a spec in your profile.":
        "Um dich für mehrere Raids anzumelden, brauchst du Charaktere mit Spec in deinem Profil.",
    "There are no coming raids with an EventHelper signup right now.": "Gerade gibt es keine kommenden Raids mit EventHelper-Anmeldung.",
    // the talk overview's raid select
    "No raid picked.": "Kein Raid gewählt.",
    "this raid": "diesen Raid",
    "Signups for {name} run through Raid-Helper – sign up in the event channel.":
        "Die Anmeldung für {name} läuft über Raid-Helper – melde dich im Event-Kanal an.",
    "Signups for {name} run through Raid-Helper. You can find the raid in the EventHelper.":
        "Die Anmeldung für {name} läuft über Raid-Helper. Den Raid findest du im EventHelper.",
    "Sign up at Raid-Helper": "Bei Raid-Helper anmelden",
    "Go to the event channel": "Zum Event-Kanal",
    // the access refusal
    "This is reserved for admins.": "Das ist den Admins vorbehalten.",
    "unknown role": "unbekannte Rolle",
    "{first} or {last}": "{first} oder {last}",
    "You need {roles} for this.": "Dafür brauchst du {roles}.",
    // the note post in the orga's channel (server language)
    "Notification received!": "Benachrichtigung erhalten!",
    "{who} signed up as {status} with the following reason:": "{who} hat sich als {status} gemeldet, mit folgender Begründung:",
    "Absent": "Abgemeldet",
};
